name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Installaion
      run: |
        python setup.py
    
    - uses: github/super-linter@v2.2.2
    - name: linting
