name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Installaion
      run: |
        dpkg-buildpackage -b
        cd ..
        sudo dpkg -i facerec_*.deb

