name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Installaion
      run: |
        sudo apt-get install dh-make debhelper python3-pip python3-opencv cmake libatlas-base-dev build-essential python-execnet
        sudo -H pip3 install setuptools
        dpkg-buildpackage -b
        cd ..
        sudo dpkg -i facerec_*.deb

    - name: Dependencies check
      run: |
        python3 /lib/Auth/Facerec/getFaces.py
        python3 /lib/Auth/Facerec/pam_ptn.py
